import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { parse as parseYaml } from "yaml";

import { listInScopeFiles } from "../scripts/file-manifest.js";
import { CONVENTION_MAX_BODY_LINES } from "./validate.js";

/**
 * Extensions counted as source when sizing a corpus.
 *
 * Deliberately code only. `.yaml`/`.yml` are excluded: on a repository that has
 * not ignored them, a lock file or a CI matrix would raise the ceiling far more
 * than it adds documentable domain, and a ceiling is only useful if it tracks
 * the amount of behaviour a reader has to understand.
 */
export const SOURCE_EXTENSIONS = [
  ".ts",
  ".tsx",
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".py",
  ".rb",
  ".go",
  ".rs",
  ".java",
  ".kt",
  ".swift",
  ".cs",
  ".php",
  ".scala",
  ".sh",
  ".sql",
  ".vue",
  ".svelte",
];

/**
 * Doc-lines allowed per source line, and source lines per document.
 *
 * Calibrated against this repository's own regenerations: ~13.6k source lines
 * should permit ~32 documents and ~3.4k documented lines. Tests are excluded
 * from the measurement (see `isTestPath`), so the ratio is against the code a
 * corpus actually describes.
 */
export const DOC_LINES_PER_SOURCE_LINE = 0.25;
export const SOURCE_LINES_PER_DOC = 420;

/**
 * Floors, so a small project is not handed an unusable budget. Without them a
 * 1,000-line app would be allowed two documents, which no corpus can satisfy.
 */
export const MIN_DOC_CEILING = 8;
export const MIN_LINE_CEILING = 400;

/** Generated by the navigation layer and the templates, never authored by a plan. */
const GENERATED_DOC_NAMES = ["INDEX.md", "README.md", "GLOSSARY.md"];

export interface SourceMeasurement {
  files: number;
  lines: number;
}

export interface Ceilings {
  docs: number;
  lines: number;
}

/**
 * True for paths conventionally holding tests rather than the domain a corpus
 * documents. Tests describe the code; they are not themselves a subject the
 * documentation covers, and counting them would let test volume buy a bigger
 * corpus.
 */
export function isTestPath(relPath: string): boolean {
  const segments = relPath.split("/");
  const file = segments[segments.length - 1];

  if (segments.slice(0, -1).some((s) => TEST_DIR_NAMES.includes(s))) return true;
  return /\.(test|spec)\./.test(file);
}

const TEST_DIR_NAMES = ["test", "tests", "spec", "specs", "__tests__", "__mocks__"];

export function isSourceFile(relPath: string): boolean {
  const lower = relPath.toLowerCase();
  return SOURCE_EXTENSIONS.some((ext) => lower.endsWith(ext)) && !isTestPath(relPath);
}

/**
 * Count the source lines under `appDir`, honouring the same ignore rules as the
 * baseline manifest.
 */
export async function measureSource(
  appDir: string,
  docsDir: string,
): Promise<SourceMeasurement> {
  const paths = (await listInScopeFiles(appDir, docsDir)).filter(isSourceFile);

  let lines = 0;
  for (const rel of paths) {
    let content: string;
    try {
      content = await readFile(join(appDir, rel), "utf8");
    } catch {
      // A dangling symlink or an unreadable file is not worth failing a run
      // over: it contributes nothing to the ceiling either way.
      continue;
    }
    lines += countLines(content);
  }

  return { files: paths.length, lines };
}

function countLines(content: string): number {
  if (content === "") return 0;
  const newlines = content.split("\n").length - 1;
  return content.endsWith("\n") ? newlines : newlines + 1;
}

/**
 * Derive the corpus ceilings from a source measurement.
 *
 * The formula lives here and nowhere else: a plan may state its own totals, but
 * they are informational, and a gate that trusted them would be enforcing the
 * planner's opinion of the budget rather than the budget.
 */
export function deriveCeilings(measurement: SourceMeasurement): Ceilings {
  if (measurement.lines === 0) return { docs: 0, lines: 0 };

  return {
    docs: Math.max(MIN_DOC_CEILING, Math.round(measurement.lines / SOURCE_LINES_PER_DOC)),
    lines: Math.max(
      MIN_LINE_CEILING,
      Math.round(measurement.lines * DOC_LINES_PER_SOURCE_LINE),
    ),
  };
}

/**
 * The Core band's ceiling, charged to a document the plan lists but never
 * budgets. Charging zero would make an unbudgeted document free, which is the
 * cheapest possible way for a planner to evade the corpus ceiling.
 */
export const UNBUDGETED_CHARGE = 200;

export interface PlannedDoc {
  /** Normalized, docs-dir-relative path. */
  path: string;
  /** Lines the plan assigned, or null when it assigned none. */
  budget: number | null;
  isConvention: boolean;
  hasOwns: boolean;
}

export interface PlanParse {
  docs: PlannedDoc[];
  sawBudgetLine: boolean;
  sawOwnsLine: boolean;
  /** Bare basenames matching more than one qualified document. */
  ambiguous: string[];
}

const DASH = String.raw`[—–‒−-]{1,3}`;
const LEAD = String.raw`^\s*(?:[-*+]\s+)?(?:\*\*|__|\x60)?\s*`;
const PATH_TOKEN = String.raw`([^\s\x60*]+\.md)`;
const TRAIL = String.raw`(?:\*\*|__|\x60)?\s*`;

const BUDGET_TIERED = new RegExp(
  `${LEAD}${PATH_TOKEN}${TRAIL}${DASH}` +
    String.raw`\s*(?:Core|Supporting|Peripheral)\s*[,:]?\s*(\d+)\s*lines?\b`,
  "i",
);
const BUDGET_TIERLESS = new RegExp(
  `${LEAD}${PATH_TOKEN}${TRAIL}${DASH}` + String.raw`\s*(\d+)\s*lines?\b`,
  "i",
);
const OWNS_LINE = new RegExp(
  `${LEAD}${PATH_TOKEN}${TRAIL}${DASH}` + String.raw`\s*owns\s*:`,
  "i",
);
const MD_TOKEN = /[^\s`*()[\],;"']+\.md/gi;

/**
 * Drop fenced code blocks. The plan carries a YAML frontmatter example inside a
 * fence, and anything document-shaped inside one is illustration, not a decision.
 */
function stripFences(text: string): string {
  const out: string[] = [];
  let inFence = false;
  for (const line of text.split("\n")) {
    if (/^\s*(```|~~~)/.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (!inFence) out.push(line);
  }
  return out.join("\n");
}

/**
 * Normalize a path as written in a plan to a docs-dir-relative key.
 *
 * The prompts model three different path forms — a bare basename in the worked
 * budget example, a `{docs_dir}`-prefixed path for conventions, and nothing at
 * all for concepts, patterns and features — so the same document routinely
 * appears in two forms within one plan.
 */
export function normalizeDocPath(raw: string, docsDir: string): string | null {
  let p = raw.trim().replace(/^\/+/, "");
  for (const prefix of [`${docsDir}/`, "{docs_dir}/", "<docs_dir>/"]) {
    if (p.startsWith(prefix)) {
      p = p.slice(prefix.length);
      break;
    }
  }
  p = p
    .split("/")
    .filter((s) => s !== "" && s !== ".")
    .join("/");
  return p.toLowerCase().endsWith(".md") ? p : null;
}

function isGenerated(path: string): boolean {
  const base = (path.split("/").pop() ?? "").toLowerCase();
  return GENERATED_DOC_NAMES.some((n) => n.toLowerCase() === base);
}

function isConventionPath(path: string): boolean {
  return path.startsWith("conventions/");
}

/**
 * Build the roster of documents a plan authors, with the lines each will cost.
 *
 * The roster is the union of three independent sets because no one of them is
 * complete: convention documents get neither a budget line nor an ownership
 * line (the conventions phase emits only a bare path), while concepts, patterns
 * and features get both.
 */
export function parsePlannedDocs(planText: string, docsDir: string): PlanParse {
  const body = stripFences(planText);
  const byPath = new Map<string, PlannedDoc>();
  let sawBudgetLine = false;
  let sawOwnsLine = false;

  const upsert = (path: string): PlannedDoc => {
    let doc = byPath.get(path);
    if (!doc) {
      doc = { path, budget: null, isConvention: isConventionPath(path), hasOwns: false };
      byPath.set(path, doc);
    }
    return doc;
  };

  for (const line of body.split("\n")) {
    // Only the left-hand side of a line is ever a document: a `references:`
    // right-hand side names other documents, and counting those would inflate
    // the roster with documents this line does not create. Both patterns are
    // anchored at line start, so a right-hand side can never match.
    const budget = BUDGET_TIERED.exec(line) ?? BUDGET_TIERLESS.exec(line);
    if (budget) {
      const path = normalizeDocPath(budget[1], docsDir);
      if (path && !isGenerated(path)) {
        sawBudgetLine = true;
        const doc = upsert(path);
        const n = Number.parseInt(budget[2], 10);
        if (Number.isFinite(n)) doc.budget = Math.max(doc.budget ?? 0, n);
      }
      continue;
    }

    const owns = OWNS_LINE.exec(line);
    if (owns) {
      const path = normalizeDocPath(owns[1], docsDir);
      if (path && !isGenerated(path)) {
        sawOwnsLine = true;
        upsert(path).hasOwns = true;
      }
    }
  }

  // Conventions, found anywhere in the body — they get no line of their own.
  for (const match of body.matchAll(MD_TOKEN)) {
    const path = normalizeDocPath(match[0], docsDir);
    if (path && isConventionPath(path) && !isGenerated(path)) upsert(path);
  }

  return { ...collapseBasenames(byPath), sawBudgetLine, sawOwnsLine };
}

/**
 * Merge a bare-basename entry into the qualified entry it names.
 *
 * Without this, a plan writing `foo.md` on the budget line and
 * `concepts/foo.md` on the ownership line counts as two documents, one of them
 * unbudgeted — a phantom overage that would fail a perfectly good plan.
 */
function collapseBasenames(byPath: Map<string, PlannedDoc>): {
  docs: PlannedDoc[];
  ambiguous: string[];
} {
  const qualified = [...byPath.keys()].filter((p) => p.includes("/"));
  const ambiguous: string[] = [];

  for (const bare of [...byPath.keys()].filter((p) => !p.includes("/"))) {
    const candidates = qualified.filter((q) => q.split("/").pop() === bare);
    if (candidates.length === 0) continue;
    if (candidates.length > 1) {
      ambiguous.push(bare);
      continue;
    }
    const from = byPath.get(bare);
    const into = byPath.get(candidates[0]);
    if (!from || !into) continue;
    into.budget = into.budget ?? from.budget;
    into.hasOwns = into.hasOwns || from.hasOwns;
    byPath.delete(bare);
  }

  return {
    docs: [...byPath.values()].sort((a, b) => a.path.localeCompare(b.path)),
    ambiguous,
  };
}

/** Lines a planned document is charged against the corpus line ceiling. */
export function docCost(doc: PlannedDoc): number {
  if (doc.isConvention) return CONVENTION_MAX_BODY_LINES;
  return doc.budget ?? UNBUDGETED_CHARGE;
}

export type BudgetStatus = "PASS" | "OVER" | "UNPARSEABLE";

export type BudgetReason =
  | "no-measurable-source"
  | "over-doc-count"
  | "over-line-budget"
  | "unbudgeted"
  | "ambiguous-path"
  | "empty-roster"
  | "one-sided-roster";

export interface BudgetReport {
  status: BudgetStatus;
  reasons: BudgetReason[];
  docs: number;
  lines: number;
  ceilings: Ceilings;
  source: SourceMeasurement;
  unbudgeted: string[];
  ambiguous: string[];
}

/**
 * Decide a plan against the ceilings. Collects rather than throws — deciding
 * which problems are fatal belongs to the caller, which knows whether it is
 * reporting inside a retry loop or enforcing after it.
 */
export function checkPlanBudget(
  parse: PlanParse,
  ceilings: Ceilings,
  source: SourceMeasurement,
  nonZeroPhaseCount: number,
): BudgetReport {
  const reasons: BudgetReason[] = [];
  const unbudgeted = parse.docs
    .filter((d) => !d.isConvention && d.budget === null)
    .map((d) => d.path);

  const docs = parse.docs.length;
  const lines = parse.docs.reduce((sum, d) => sum + docCost(d), 0);

  const base: Omit<BudgetReport, "status" | "reasons"> = {
    docs,
    lines,
    ceilings,
    source,
    unbudgeted,
    ambiguous: parse.ambiguous,
  };

  // A repository with no measurable source has no ceiling to derive, and a
  // ceiling of zero would fail every plan written against it.
  if (source.lines === 0) {
    return { ...base, status: "PASS", reasons: ["no-measurable-source"] };
  }

  // Parser drift. A plan whose decisions this gate cannot read has not been
  // checked, and passing it silently would make the whole gate decorative.
  if (parse.docs.length === 0 && nonZeroPhaseCount > 0) {
    return { ...base, status: "UNPARSEABLE", reasons: ["empty-roster"] };
  }
  if (parse.sawBudgetLine !== parse.sawOwnsLine && parse.docs.length > 0) {
    return { ...base, status: "UNPARSEABLE", reasons: ["one-sided-roster"] };
  }

  if (parse.ambiguous.length > 0) reasons.push("ambiguous-path");
  if (unbudgeted.length > 0) reasons.push("unbudgeted");
  if (docs > ceilings.docs) reasons.push("over-doc-count");
  if (lines > ceilings.lines) reasons.push("over-line-budget");

  const over = reasons.includes("over-doc-count") || reasons.includes("over-line-budget");
  return { ...base, status: over ? "OVER" : "PASS", reasons };
}

/**
 * Phase numbers other than 0 declared in the plan's frontmatter. Read here
 * rather than taken from `parse-plan`'s output so the gate is self-contained:
 * it is checking whether it understood the plan at all.
 */
export function countNonZeroPhases(planText: string): number {
  const match = /^---\n([\s\S]*?)\n---/.exec(planText);
  if (!match) return 0;
  try {
    const data = parseYaml(match[1]) as { phases?: { number?: number }[] } | null;
    const phases = data?.phases;
    if (!Array.isArray(phases)) return 0;
    return phases.filter((p) => Number(p?.number) !== 0).length;
  } catch {
    return 0;
  }
}
