import { lstat, readFile } from "node:fs/promises";
import { join } from "node:path";
import { parse as parseYaml } from "yaml";

import { listInScopeFiles } from "../scripts/file-manifest.js";
import { CONVENTION_MAX_BODY_LINES } from "./validate.js";

/**
 * Extensions counted as source when sizing a corpus.
 *
 * Deliberately code only. `.yaml`/`.yml` are excluded: on a repository that has
 * not ignored them, a lock file or a CI matrix would raise the ceiling far more
 * than it adds documentable domain, and a ceiling is only useful if it tracks
 * the amount of behaviour a reader has to understand.
 *
 * An allowlist will always trail some language, and a stack it does not
 * recognise measures zero — which passes every plan. That failure is silent by
 * construction, so the gate reports it (`no-measurable-source`) rather than
 * treating it as an ordinary pass; adding an extension here is the fix.
 */
export const SOURCE_EXTENSIONS = [
  // Web / scripting
  ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".mts", ".cts",
  ".vue", ".svelte", ".astro",
  ".py", ".rb", ".php", ".pl", ".pm", ".lua", ".r",
  // Systems / compiled
  ".c", ".h", ".cc", ".cpp", ".cxx", ".hh", ".hpp", ".hxx",
  ".go", ".rs", ".zig", ".d", ".nim", ".cr",
  // JVM / .NET
  ".java", ".kt", ".kts", ".scala", ".groovy", ".clj", ".cljs", ".cljc",
  ".cs", ".fs", ".fsx", ".vb",
  // Apple / mobile
  ".swift", ".m", ".mm", ".dart",
  // Functional / other
  ".ex", ".exs", ".erl", ".hrl", ".hs", ".ml", ".mli", ".elm", ".jl",
  // Shell and data access
  ".sh", ".bash", ".zsh", ".ps1", ".sql",
];

/**
 * Doc-lines allowed per source line, and source lines per document.
 *
 * Calibrated against this repository's own regenerations: ~13.6k source lines
 * should permit ~32 documents and ~3.4k documented lines. Tests are excluded
 * from the measurement (see `isTestPath`), so the ratio is against the code a
 * corpus actually describes.
 */
export const DOC_LINES_PER_SOURCE_LINE = 0.25;
export const SOURCE_LINES_PER_DOC = 420;

/**
 * Floors, so a small project is not handed an unusable budget. Without them a
 * 1,000-line app would be allowed two documents, which no corpus can satisfy.
 */
export const MIN_DOC_CEILING = 8;
export const MIN_LINE_CEILING = 400;

/** Generated by the navigation layer and the templates, never authored by a plan. */
const GENERATED_DOC_NAMES = ["INDEX.md", "README.md", "GLOSSARY.md"];

export interface SourceMeasurement {
  files: number;
  lines: number;
}

export interface Ceilings {
  docs: number;
  lines: number;
}

/**
 * True for paths conventionally holding tests rather than the domain a corpus
 * documents. Tests describe the code; they are not themselves a subject the
 * documentation covers, and counting them would let test volume buy a bigger
 * corpus.
 */
export function isTestPath(relPath: string): boolean {
  const segments = relPath.split("/");
  const file = segments[segments.length - 1];

  if (segments.slice(0, -1).some((s) => TEST_DIR_NAMES.includes(s))) return true;
  return TEST_FILE_PATTERNS.some((re) => re.test(file));
}

const TEST_DIR_NAMES = ["test", "tests", "spec", "specs", "__tests__", "__mocks__"];

/**
 * Test-file naming, which is language convention rather than one rule. Go and
 * Rust put `foo_test.go` beside the code it tests, Python uses `test_foo.py`,
 * and the JVM/.NET world capitalises a suffix — none of which look like the
 * JavaScript `foo.test.ts`. Missing any of them lets test volume buy a bigger
 * corpus, which is the thing this exclusion exists to prevent.
 */
const TEST_FILE_PATTERNS = [
  /\.(test|spec)\./i,
  /_(test|spec)\.[a-z0-9]+$/i,
  /^test_[^/]*\.[a-z0-9]+$/i,
  /^(?:.*[a-z0-9])(?:Test|Tests|Spec)\.[a-z0-9]+$/,
];

export function isSourceFile(relPath: string): boolean {
  const lower = relPath.toLowerCase();
  return SOURCE_EXTENSIONS.some((ext) => lower.endsWith(ext)) && !isTestPath(relPath);
}

/**
 * Count the source lines under `appDir`, honouring the same ignore rules as the
 * baseline manifest.
 */
export async function measureSource(
  appDir: string,
  docsDir: string,
): Promise<SourceMeasurement> {
  const paths = (await listInScopeFiles(appDir, docsDir)).filter(isSourceFile);

  let files = 0;
  let lines = 0;
  for (const rel of paths) {
    const abs = join(appDir, rel);
    let content: string;
    try {
      // Never dereference a symlink. The manifest hashes the link target
      // string rather than following it, and following one here would count an
      // ignored file, count an in-repo file twice, or pull an entirely
      // external file into the ceiling.
      if ((await lstat(abs)).isSymbolicLink()) continue;
      content = await readFile(abs, "utf8");
    } catch {
      // A dangling link or an unreadable file is not worth failing a run over:
      // it contributes nothing to the ceiling either way.
      continue;
    }
    files += 1;
    lines += countLines(content);
  }

  return { files, lines };
}

function countLines(content: string): number {
  if (content === "") return 0;
  const newlines = content.split("\n").length - 1;
  return content.endsWith("\n") ? newlines : newlines + 1;
}

/**
 * Derive the corpus ceilings from a source measurement.
 *
 * The formula lives here and nowhere else: a plan may state its own totals, but
 * they are informational, and a gate that trusted them would be enforcing the
 * planner's opinion of the budget rather than the budget.
 */
export function deriveCeilings(measurement: SourceMeasurement): Ceilings {
  if (measurement.lines === 0) return { docs: 0, lines: 0 };

  return {
    docs: Math.max(MIN_DOC_CEILING, Math.round(measurement.lines / SOURCE_LINES_PER_DOC)),
    lines: Math.max(
      MIN_LINE_CEILING,
      Math.round(measurement.lines * DOC_LINES_PER_SOURCE_LINE),
    ),
  };
}

/**
 * The Core band's ceiling, charged to a document the plan lists but never
 * budgets. Charging zero would make an unbudgeted document free, which is the
 * cheapest possible way for a planner to evade the corpus ceiling.
 */
export const UNBUDGETED_CHARGE = 200;

/**
 * The floor of each tier's band, from the level-of-detail policy. A budget
 * below its own tier is charged the floor: the tiers come from centrality, so
 * "Core, 1 line" is not a small Core document, it is a misdeclared one — and
 * without this the total-line ceiling could be met by shrinking numbers rather
 * than cutting documents, which is the one response the policy rules out.
 */
export const TIER_MINIMUM_LINES: Record<string, number> = {
  core: 100,
  supporting: 60,
  peripheral: 25,
};

export interface PlannedDoc {
  /** Normalized, docs-dir-relative path. */
  path: string;
  /** Lines the plan assigned, or null when it assigned none. */
  budget: number | null;
  /** Lowercased tier from the budget line, absent for ARCHITECTURE. */
  tier: string | null;
  isConvention: boolean;
  hasOwns: boolean;
}

export interface PlanParse {
  docs: PlannedDoc[];
  sawBudgetLine: boolean;
  sawOwnsLine: boolean;
  /** Bare basenames matching more than one qualified document. */
  ambiguous: string[];
}

const DASH = String.raw`[—–‒−-]{1,3}`;
const LEAD = String.raw`^\s*(?:[-*+]\s+)?(?:\*\*|__|\x60)?\s*`;
const PATH_TOKEN = String.raw`([^\s\x60*]+\.md)`;
const TRAIL = String.raw`(?:\*\*|__|\x60)?\s*`;

const BUDGET_TIERED = new RegExp(
  `${LEAD}${PATH_TOKEN}${TRAIL}${DASH}` +
    String.raw`\s*(Core|Supporting|Peripheral)\s*[,:]?\s*(\d+)\s*lines?\b`,
  "i",
);
const BUDGET_TIERLESS = new RegExp(
  `${LEAD}${PATH_TOKEN}${TRAIL}${DASH}` + String.raw`\s*(\d+)\s*lines?\b`,
  "i",
);
const OWNS_LINE = new RegExp(
  `${LEAD}${PATH_TOKEN}${TRAIL}${DASH}` + String.raw`\s*owns\s*:`,
  "i",
);
const MD_TOKEN = /[^\s`*()[\],;"']+\.md/gi;

/**
 * Drop fenced code blocks. The plan carries a YAML frontmatter example inside a
 * fence, and anything document-shaped inside one is illustration, not a decision.
 */
function stripFences(text: string): string {
  const out: string[] = [];
  let inFence = false;
  for (const line of text.replace(/\r\n?/g, "\n").split("\n")) {
    if (/^\s*(```|~~~)/.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (!inFence) out.push(line);
  }
  return out.join("\n");
}

/**
 * Normalize a path as written in a plan to a docs-dir-relative key.
 *
 * The prompts model three different path forms — a bare basename in the worked
 * budget example, a `{docs_dir}`-prefixed path for conventions, and nothing at
 * all for concepts, patterns and features — so the same document routinely
 * appears in two forms within one plan.
 */
export function normalizeDocPath(raw: string, docsDir: string): string | null {
  let p = raw.trim().replace(/^\/+/, "");
  for (const prefix of [`${docsDir}/`, "{docs_dir}/", "<docs_dir>/"]) {
    if (p.startsWith(prefix)) {
      p = p.slice(prefix.length);
      break;
    }
  }
  p = p
    .split("/")
    .filter((s) => s !== "" && s !== ".")
    .join("/");
  return p.toLowerCase().endsWith(".md") ? p : null;
}

/**
 * Drop backticks and emphasis *wrapping* a path. Anchored at the ends, never
 * global: underscores are ordinary characters inside a filename, and stripping
 * them everywhere turns `{docs_dir}/x.md` into an unrecognisable path.
 */
function stripDecoration(text: string): string {
  return text.trim().replace(/^[`*_]+/, "").replace(/[`*_]+$/, "");
}

function isGenerated(path: string): boolean {
  const base = (path.split("/").pop() ?? "").toLowerCase();
  return GENERATED_DOC_NAMES.some((n) => n.toLowerCase() === base);
}

function isConventionPath(path: string): boolean {
  return path.startsWith("conventions/");
}

/**
 * Build the roster of documents a plan authors, with the lines each will cost.
 *
 * The roster is the union of three independent sets because no one of them is
 * complete: convention documents get neither a budget line nor an ownership
 * line (the conventions phase emits only a bare path), while concepts, patterns
 * and features get both.
 */
export function parsePlannedDocs(planText: string, docsDir: string): PlanParse {
  const body = stripFences(planText);
  const byPath = new Map<string, PlannedDoc>();
  let sawBudgetLine = false;
  let sawOwnsLine = false;

  const upsert = (path: string): PlannedDoc => {
    let doc = byPath.get(path);
    if (!doc) {
      doc = {
        path,
        budget: null,
        tier: null,
        isConvention: isConventionPath(path),
        hasOwns: false,
      };
      byPath.set(path, doc);
    }
    return doc;
  };

  for (const line of body.split("\n")) {
    // Only the left-hand side of a line is ever a document: a `references:`
    // right-hand side names other documents, and counting those would inflate
    // the roster with documents this line does not create. Both patterns are
    // anchored at line start, so a right-hand side can never match.
    const tiered = BUDGET_TIERED.exec(line);
    const budget = tiered ?? BUDGET_TIERLESS.exec(line);
    if (budget) {
      // Tiered: [path, tier, lines]. Tier-less (ARCHITECTURE): [path, lines].
      const rawTier = tiered ? tiered[2] : null;
      const rawLines = tiered ? tiered[3] : budget[2];

      const path = normalizeDocPath(budget[1], docsDir);
      if (path && !isGenerated(path)) {
        sawBudgetLine = true;
        const doc = upsert(path);
        if (rawTier) doc.tier = rawTier.toLowerCase();
        const n = Number.parseInt(rawLines, 10);
        if (Number.isFinite(n)) doc.budget = Math.max(doc.budget ?? 0, n);
      }
      continue;
    }

    const owns = OWNS_LINE.exec(line);
    if (owns) {
      const path = normalizeDocPath(owns[1], docsDir);
      if (path && !isGenerated(path)) {
        sawOwnsLine = true;
        upsert(path).hasOwns = true;
      }
    }
  }

  // Conventions get neither a budget nor an ownership line — the conventions
  // phase lists them as bare deliverables. Only a line that is *just* such a
  // path counts: a convention named inside an `owns:`/`references:` line or in
  // prose is being referred to, not created, and counting those would cost
  // three re-plans and a failure over documents the plan never makes.
  for (const raw of body.split("\n")) {
    const line = raw.trim().replace(/^[-*+]\s+/, "");
    if (/owns\s*:|references\s*:/i.test(line)) continue;

    const tokens = [...line.matchAll(MD_TOKEN)].map((m) => m[0]);
    if (tokens.length !== 1) continue;

    const path = normalizeDocPath(stripDecoration(tokens[0]), docsDir);
    if (!path || !isConventionPath(path) || isGenerated(path)) continue;

    // The path must be effectively the whole line, so a sentence merely
    // mentioning one document does not create it.
    if (stripDecoration(line).replace(/[.,;:]$/, "") !== stripDecoration(tokens[0])) continue;
    upsert(path);
  }

  return { ...collapseBasenames(byPath), sawBudgetLine, sawOwnsLine };
}

/**
 * Merge a bare-basename entry into the qualified entry it names.
 *
 * Without this, a plan writing `foo.md` on the budget line and
 * `concepts/foo.md` on the ownership line counts as two documents, one of them
 * unbudgeted — a phantom overage that would fail a perfectly good plan.
 */
function collapseBasenames(byPath: Map<string, PlannedDoc>): {
  docs: PlannedDoc[];
  ambiguous: string[];
} {
  const qualified = [...byPath.keys()].filter((p) => p.includes("/"));
  const ambiguous: string[] = [];

  for (const bare of [...byPath.keys()].filter((p) => !p.includes("/"))) {
    const candidates = qualified.filter((q) => q.split("/").pop() === bare);
    if (candidates.length === 0) continue;
    if (candidates.length > 1) {
      ambiguous.push(bare);
      continue;
    }
    const from = byPath.get(bare);
    const into = byPath.get(candidates[0]);
    if (!from || !into) continue;
    into.budget = into.budget ?? from.budget;
    into.hasOwns = into.hasOwns || from.hasOwns;
    byPath.delete(bare);
  }

  return {
    docs: [...byPath.values()].sort((a, b) => a.path.localeCompare(b.path)),
    ambiguous,
  };
}

/** Lines a planned document is charged against the corpus line ceiling. */
export function docCost(doc: PlannedDoc): number {
  if (doc.isConvention) return CONVENTION_MAX_BODY_LINES;
  if (doc.budget === null) return UNBUDGETED_CHARGE;

  const floor = doc.tier ? TIER_MINIMUM_LINES[doc.tier] : undefined;
  return floor === undefined ? doc.budget : Math.max(doc.budget, floor);
}

/** True when a budget sits below the floor of the tier it declares. */
export function isBelowTier(doc: PlannedDoc): boolean {
  const floor = doc.tier ? TIER_MINIMUM_LINES[doc.tier] : undefined;
  return floor !== undefined && doc.budget !== null && doc.budget < floor;
}

export type BudgetStatus = "PASS" | "OVER" | "UNPARSEABLE";

export type BudgetReason =
  | "no-measurable-source"
  | "over-doc-count"
  | "over-line-budget"
  | "unbudgeted"
  | "below-tier"
  | "ambiguous-path"
  | "empty-roster"
  | "one-sided-roster";

export interface BudgetReport {
  status: BudgetStatus;
  reasons: BudgetReason[];
  docs: number;
  lines: number;
  ceilings: Ceilings;
  source: SourceMeasurement;
  unbudgeted: string[];
  /** Documents whose budget sits below the floor of the tier they declare. */
  belowTier: string[];
  ambiguous: string[];
}

/**
 * Decide a plan against the ceilings. Collects rather than throws — deciding
 * which problems are fatal belongs to the caller, which knows whether it is
 * reporting inside a retry loop or enforcing after it.
 */
export function checkPlanBudget(
  parse: PlanParse,
  ceilings: Ceilings,
  source: SourceMeasurement,
  nonZeroPhaseCount: number,
): BudgetReport {
  const reasons: BudgetReason[] = [];
  const unbudgeted = parse.docs
    .filter((d) => !d.isConvention && d.budget === null)
    .map((d) => d.path);

  const docs = parse.docs.length;
  const lines = parse.docs.reduce((sum, d) => sum + docCost(d), 0);

  const base: Omit<BudgetReport, "status" | "reasons"> = {
    docs,
    lines,
    ceilings,
    source,
    unbudgeted,
    belowTier: parse.docs.filter(isBelowTier).map((d) => d.path),
    ambiguous: parse.ambiguous,
  };

  // A repository with no measurable source has no ceiling to derive, and a
  // ceiling of zero would fail every plan written against it.
  if (source.lines === 0) {
    return { ...base, status: "PASS", reasons: ["no-measurable-source"] };
  }

  // Parser drift. A plan whose decisions this gate cannot read has not been
  // checked, and passing it silently would make the whole gate decorative.
  if (parse.docs.length === 0 && nonZeroPhaseCount > 0) {
    return { ...base, status: "UNPARSEABLE", reasons: ["empty-roster"] };
  }
  if (parse.sawBudgetLine !== parse.sawOwnsLine && parse.docs.length > 0) {
    return { ...base, status: "UNPARSEABLE", reasons: ["one-sided-roster"] };
  }

  if (parse.ambiguous.length > 0) reasons.push("ambiguous-path");
  if (unbudgeted.length > 0) reasons.push("unbudgeted");
  if (base.belowTier.length > 0) reasons.push("below-tier");
  if (docs > ceilings.docs) reasons.push("over-doc-count");
  if (lines > ceilings.lines) reasons.push("over-line-budget");

  const over = reasons.includes("over-doc-count") || reasons.includes("over-line-budget");
  return { ...base, status: over ? "OVER" : "PASS", reasons };
}

/**
 * Phase numbers other than 0 declared in the plan's frontmatter. Read here
 * rather than taken from `parse-plan`'s output so the gate is self-contained:
 * it is checking whether it understood the plan at all.
 */
export function countNonZeroPhases(planText: string): number {
  // `\r?\n` matches parse-plan: a CRLF plan it accepts must not read as
  // zero phases here, or the empty-roster guard would be skipped and an
  // unreadable plan would pass as a zero-document corpus.
  const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(planText);
  if (!match) return 0;
  try {
    const data = parseYaml(match[1]) as { phases?: { number?: number }[] } | null;
    const phases = data?.phases;
    if (!Array.isArray(phases)) return 0;
    return phases.filter((p) => Number(p?.number) !== 0).length;
  } catch {
    return 0;
  }
}
